### ISSUE TITLE
Get an error running server.js 

### ISSUE THREAD

**Issue by mew0717** [julianh2o/RokuAlexaLambdaSkill#1]
Trying to run via terminal this on my mac mini:

Here's the error message.  Any idea?

var ssdp = new Client();
           ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/mew0717/Echo/RokuSkill/server.js:11:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by julianh2o** [comment]
Hmm, you may need to run: npm install node-ssdp

**Comment by mew0717** [comment]
Nope... that didn't do it.  All I get when i run that is:
npm WARN package.json RokuControlServer@0.0.1 'repositories' (plural) Not supported. Please pick one as the 'repository' field
npm WARN package.json RokuControlServer@0.0.1 No README data
npm WARN package.json RokuControlServer@0.0.1 No license field.

**Comment by julianh2o** [comment]
Oops, I've just pushed a revision to fix this. The package.json file had the wrong version of node-ssdp listed!

Thanks for the report and best of luck getting this running!
